#!/usr/bin/env python
# coding: utf-8

# In[1]:


import numpy as np ####### Linear algebra #######
import pandas as pd ######## a data processing tool for CSV I/O library #####
import warnings ########## ignore warnings generated by seaborn
warnings.filterwarnings('ignore')

############ data visualization #######
import seaborn as sns
import matplotlib.pyplot as plt
get_ipython().run_line_magic('matplotlib', 'inline')
sns.set(style = 'white', color_codes = True)


# In[2]:


###### loading the dataset
df = "C:/Users/ALEX/Desktop/IRIS.csv"
df = pd.read_csv(df)
print(df)


# In[3]:


df.head()


# In[7]:


df.hist(edgecolor='black', linewidth=1.2)
fig = plt.gcf()
fig.set_size_inches(12,6)
plt.show()


# In[14]:


plt.figure(figsize=(8,4))
sns.heatmap(df.corr(), annot=True, cmap='cubehelix_r') # draws heatmap with input as correlation matrix calculated by df.corr() 
plt.show()


# In[15]:


df.info()


# In[ ]:




